#################################################################################################
# LOCAL HOST ROUTES:
#################################################################################################
# GET REQUEST TO SEE ALL CONTACTS IN THE CONTACT LIST:
###
GET http://localhost:3000/contacts HTTP/1.1

# GET REQUEST TO SEE A SINGLE CONTACT IN THE CONTACT LIST:
###
GET http://localhost:3000/contact/645309e7867cdd68c443a0dc HTTP/1.1

# POST REQUEST TO ADD A NEW CONTACT TO THE CONTACTS LIST.
###
POST http://localhost:3000/contact HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Marley",
    "email": "thebob@test.com",
    "color": "Blue",
    "birthday": "1964-12-09"
}
###
POST http://localhost:3000/contact HTTP/1.1
Content-Type: application/json

{
  "firstName": "Excellent",
  "lastName": "Tryyyy",
  "email": "any@gmail.com",
  "color": "greeen",
  "birthday": "2013-05-26"

}
###
POST http://localhost:3000/contact HTTP/1.1
Content-Type: application/json

{
    "firstName": "Chase",
    "lastName": "Forever",
    "email": "thechase@test.com",
    "color": "Yellow",
    "birthday": "1994-11-11"
}

###
POST http://localhost:3000/contact HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mother",
    "lastName": "Teresa",
    "email": "theteresita@test.com",
    "color": "White",
    "birthday": "1894-13-01"
}

# PUT REQUEST TO UPDATE A CONTACT IN THE CONTACT LIST:
###
PUT http://localhost:3000/contact/645f0e7f636675a6eb04edbd HTTP/1.1
Content-Type: application/json

{

    "color": "Amraillo"
}

# DELETE REQUEST TO REMOVE A CONTACT FROM THE CONTACT LIST:
###
DELETE http://localhost:3000/contact/6470246712d86ea8a0805257 HTTP/1.1


#################################################################################################
# RENDER ROUTES:
#################################################################################################
# GET REQUEST TO SEE ALL CONTACTS IN THE CONTACT LIST:
###
GET https://cse341-dn5l.onrender.com/contacts HTTP/1.1

# GET REQUEST TO SEE A SINGLE CONTACT IN THE CONTACT LIST:
###
GET https://cse341-dn5l.onrender.com/contact/645309e7867cdd68c443a0dc HTTP/1.1

# POST REQUEST TO ADD A NEW CONTACT TO THE CONTACTS LIST:
###
POST https://cse341-dn5l.onrender.com/contact HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bob",
    "lastName": "Marley",
    "email": "thebob@test.com",
    "color": "Blue",
    "birthday": "1964-12-09"
}
###
POST https://cse341-dn5l.onrender.com/contact HTTP/1.1
Content-Type: application/json

{
    "firstName": "Luis",
    "lastName": "Borton",
    "email": "borton@test.com",
    "color": "Red",
    "birthday": "1984-06-19"

}
###
POST https://cse341-dn5l.onrender.com/contact HTTP/1.1
Content-Type: application/json

{
    "firstName": "Chase",
    "lastName": "Forever",
    "email": "thechase@test.com",
    "color": "Yellow",
    "birthday": "1994-11-11"
}

# PUT REQUEST TO UPDATE A CONTACT IN THE CONTACT LIST:
###
PUT https://cse341-dn5l.onrender.com/contact/645309e7867cdd68c443a0dc HTTP/1.1
Content-Type: application/json

{
    "color": "Bright Blue"
}

# DELETE REQUEST TO REMOVE A CONTACT FROM THE CONTACT LIST:
###
DELETE https://cse341-dn5l.onrender.com/contact/645309e7867cdd68c443a0dc HTTP/1.1